### ISSUE TITLE
Array of strings and Multi Dimensional arrays

### ISSUE THREAD

**Issue by Rechdan** [januwA/struct-buffer#1]
So my question is that if there is a way of doing and array of string and an array of an array?

Thanks!

**Comment by januwA** [comment]
demo 1:
```ts
import { string_t, StructBuffer } from "struct-buffer";

const s_name = new StructBuffer("NAME", {
  name: string_t[3],
});
const s_names = new StructBuffer("NAMES", {
  names: s_name[4],
});

const data = s_names.decode(new Uint8Array([
  0x61,0x61,0x61,
  0x62,0x62,0x62,
  0x63,0x63,0x63,
  0x64,0x64,0x64,
]))

console.log(data);
// => 
{                   
  names: [          
    { name: 'aaa' },
    { name: 'bbb' },
    { name: 'ccc' },
    { name: 'ddd' } 
  ]                 
}
```

demo 2:
```ts
import { string_t, StructBuffer } from "struct-buffer";

const s_names = new StructBuffer("NAMES", {
  names: string_t[4][3], // length is 4, item length is 3
});


const data = s_names.decode(new Uint8Array([
  0x61,0x61,0x61,
  0x62,0x62,0x62,
  0x63,0x63,0x63,
  0x64,0x64,0x64,
]))

console.log(data);
// =>
{ names: [ 'aaa', 'bbb', 'ccc', 'ddd' ] }
```

demo 3:
```ts
import { string_t, StructBuffer } from "struct-buffer";

const s_names = new StructBuffer("NAMES", {
  names: string_t[3][2][2], // length is 3, item length is 2, item_item length is 2
});

const data = s_names.decode(new Uint8Array([
  0x61,0x61,
  0x61,0x62,

  0x62,0x62,
  0x63,0x63,

  0x63,0x64,
  0x64,0x64,
]))

console.log(data);
// =>
{ names: [ [ 'aa', 'ab' ], [ 'bb', 'cc' ], [ 'cd', 'dd' ] ] }
```

**Comment by Rechdan** [comment]
@januwA a multidimensional array of strings is working, but a multidimensional array of a struct is not:
```ts
const t1 = new StructBuffer('T1', {
	name: string_t[4][2][2][16],
	v1: ushort,
	v2: uchar[6],
});

const t2 = new StructBuffer('T2', {
	items: t1[4][18], // multi
});

console.log('bl:', t2.byteLength); // error!
```

And the working multidimensional string:
```ts
const t1 = new StructBuffer('T1', {
	name: string_t[4][2][2][16],
	v1: ushort,
	v2: uchar[6],
});

const t2 = new StructBuffer('T2', {
	items: t1[4], // single
});

console.log('bl:', t2.byteLength); // works!
```

**Comment by Rechdan** [comment]
Two things I saw just now, first is the encoding that would be a nice touch to allow us to choose the default encoding of the Buffer and the second is to "fix strings", for example, when I'm writing to a fixed size string to cut if the input is bigger or to fill with `0x0` if its shortter and when I'm reading from it to remove the `0x0` characters.

**Comment by januwA** [comment]
@Rechdan  Thank you very much for your tips, I have released a new version "v4.0.1", the above problems should be resolved

**Comment by Rechdan** [comment]
@januwA Indeed they are, the only thing I'm having trouble with now is the encoding, do you know any ways of targeting a specific encoding for strings?

**Comment by Rechdan** [comment]
I believe a good approach would be to make `string_t` a function and pass the encoding to it, what do you think? Or maybe to pass the encoding to the constructor itself hahaha

**Comment by Rechdan** [comment]
I found another problem, the strings aren't respecting its position in the struct, for exemple if I have a array of 4 strings with 16 characteres each and add for example `aaa` to the 4 of them, the output will be `aaaaaaaaaaaa`, not respecting the 16 characteres, which should output `aaa\0\0\0\0\0\0\0\0\0\0\0\0\0aaa\0\0\0\0\0\0\0\0\0\0\0\0\0aaa\0\0\0\0\0\0\0\0\0\0\0\0\0aaa\0\0\0\0\0\0\0\0\0\0\0\0\0`!

**Comment by januwA** [comment]
The behavior of "string_t" is actually the same as "char", the purpose is only to better display the string in js, such as:

```js
char[2][2].encode([0x61, 0x62])  // <61 62 00 00>
string_t[2][2].encode(["a", "b"])  // <61 62 00 00>

// struct
const MyString = new StructBuffer("MyString", { i: string_t[2] })
MyString[2].encode( ["a", "b"].map((i) => ({ i: i})) ) // <61 00 62 00>
```

**Comment by Rechdan** [comment]
@januwA  got it, but the interpretation it gives is that there will be an array of string which their sizes are 16, at least that's what I thought hahaha
