### ISSUE TITLE
Mixed endian encoding?

### ISSUE THREAD

**Issue by quartzjer** [januwA/struct-buffer#2]
First I just want to say thank you for making such a great module, it is very impressive!

Only one thing I haven't figured out how to do correctly yet: I have a struct that I need to encode as little endian, but inside of it two fields are big endian (IP address and port).

I tried making the ip and port their own struct and using .encode() first on them, but the resulting byte array gets re-endian'd when I later .encode() the larger struct.

Any suggestions?

**Comment by januwA** [comment]
```ts
import { createDataView, StructBuffer, int32_t, uint32_t } from "struct-buffer";

const s1 = new StructBuffer("s1", {
  a: int32_t,
  b: int32_t,
});
const s2 = new StructBuffer("s2", {
  ip: uint32_t,
  port: uint32_t,
});

const buf = createDataView(s1.byteLength + s2.byteLength);

s1.encode({ a: 1, b: 2 }, true, 0, buf);
s2.encode({ ip: 10, port: 100 }, false, s1.byteLength, buf);

console.log(buf);
// <01 00 00 00 02 00 00 00 00 00 00 0a 00 00 00 64>
```

Or like this

```ts
import { pack_into, createDataView, calcsize } from "struct-buffer";

const buf = createDataView(16);
const data = {
  a: 1,
  b: 2,
  ip: 10,
  port: 100,
};

pack_into("<2i", buf, 0, data.a, data.b);
pack_into(">2I", buf, calcsize("<2i"), data.ip, data.port);

console.log(buf);
// <01 00 00 00 02 00 00 00 00 00 00 0a 00 00 00 64>
```

If you have a better idea, you can tell me, there are still many features that need to be improved 😃

**Comment by januwA** [comment]
@quartzjer Upgrade to "v5.0.0", you can set `littleEndian` on `StructBuffer`, but this setting will cause the `littleEndian` parameters of `encode` and `decode` functions to become invalid

```ts
import { StructBuffer, WORD } from "struct-buffer";

const s = new StructBuffer(
  "test",
  {
    a: WORD,
    b: WORD,
    c: new StructBuffer(
      "test2",
      {
        ip: WORD,
        port: WORD,
      },
      {
        littleEndian: false,
      }
    ),
  },
  {
    littleEndian: true,
  }
);

const v = s.encode({
  a: 1,
  b: 2,
  c: {
    ip: 10,
    port: 100,
  },
});

console.log(v);
// <01 00 02 00 00 0a 00 64>
```

**Comment by quartzjer** [comment]
This feature you added has worked perfectly, thank you!
